server:
  port: 8084
  hostname: usg

spring:

  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5437/usg
    driverClassName: org.postgresql.Driver
    username: postgres
    password: asdfasdf
    ssl: false

  hikari:
    # needs the datasource ^^ to be called "datasource"
    connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
    maximum-pool-size: 35 #maximum pool size
    idle-timeout: 10000 #maximum idle time for connection
    max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
    auto-commit: true #default auto-commit behavior.

  task:
    scheduling:
      pool:
        size: 5